export type Cabin = "ECONOMY" | "BUSINESS"
export type PaxCategory = "ADULT" | "CHILD" | "INFANT" | "WSEATINFANT" | "YOUTH" | "SENIOR" | "DISABLED" | "DISABLEDCHILD" | "ESCORT" | "LARGEFAMILY" | "STATERESIDENT"
export type DocumentType = "REGULAR_PASSPORT" | "BIRTHDAY_CERTIFICATE" | "INTERNATIONAL_PASSPORT"
export type FopType = "CASH" | "BILL" | "CARD"