export type Cabin = "ECONOMY" | "BUSINESS"
export type PaxCategory =
    "ADULT"
    | "CHILD"
    | "INFANT"
    | "WSEATINFANT"
    | "YOUTH"
    | "SENIOR"
    | "DISABLED"
    | "DISABLEDCHILD"
    | "ESCORT"
    | "LARGEFAMILY"
    | "STATERESIDENT"
export type DocumentType =
    "REGULAR_PASSPORT"
    | "BIRTHDAY_CERTIFICATE"
    | "INTERNATIONAL_PASSPORT"
    | "OFFICER_ID"
    | "TEMPORARY_ID"
    | "MILITARY_ID"
    | "RESIDENCE"
    | "SEAMANS_ID"
    | "RETURN_ID"
export type FopType = "CASH" | "BILL" | "CARD"
export type PricingOption = "LOWEST_FARE" | "ALL_FARES"